listen: :443

tls:
  cert: CERT_PATH
  key: KEY_PATH

auth:
  type: password
  password: "123456"

bandwidth:
  up: 50 mbps
  down: 50 mbps

# تقليل الضغط على السيرفر
fastOpen: false

udpIdleTimeout: 60s
